### ISSUE TITLE
Adding metadata to a sound

### ISSUE THREAD

**Issue by Jacob-Burrill** [WhitmanCS370/alt-f4#21]
We need to be able to add metadata to sounds for sorting and grouping purposes. Perhaps we can implement this through CSV files related to each sound file.

**Comment by coden-s** [comment]
Command line interaction with metadata:
a way to list all of the metadata associated with one file. (--metadata <file_name>)
something like --metadata <file_name> <tag_name> <tag_value>

**Comment by coden-s** [comment]
We also need to think about what metadata is preexisting (like what tags we have normally) versus tags that users can add later (like if they want to tag things as like "dog" that isn't a default).

How would allowing user inputted metadata impact how we do search?
