### ISSUE TITLE
edit sounds

### ISSUE THREAD

**Issue by coden-s** [WhitmanCS370/alt-f4#28]
Add a new flag (or add it to playback, but would not be very extensible) that allows users to edit sounds.
Editing involves trimming sounds (related to #18)-- done with one sound
Could be done by applying predefined filters to sounds-- done with one or multiple sounds (how would we do multiple sounds)
Need to give users the option to save their results (either to the original file/first file??) #27 

Should we even let users edit multiple sounds at once? Edits done separately on different sounds could be done individually before-hand.

**Comment by coden-s** [comment]
rEcUrSiOn??? if people want to edit multiple sounds in one call, it could break up the call into different calls to edit with different sounds and edits they want to apply.

**Comment by ghost** [comment]
a good frame of reference is distinguishing between edits as being implicitly or explicitly defined. an explicit definition manually specifies an --edit flag when grouping and applying audio filter commands (would this imply grouping filters adjacent in input?). an implicit definition wouldn't bother, parses the user input (an issue in and of itself), and identifies the collection of filters as an edited object (time for us to instantiate in our refactors) in code

**Comment by Jacob-Burrill** [comment]
Wave library:
https://docs.python.org/3/library/wave.html

**Comment by ghost** [comment]
Refactor idea

Eventual Refactoring
Command order of operations
Chain of responsibility pattern
Different groupings of operations
1. Transforms
2. Output
    - Play
    - Sequential

Command processor class
- Validate method
- Process method
    - Order of operations defined by user input order
        - Transform group
        - Output group

**Comment by samuelboerner** [comment]
closed as part of restructure
