### ISSUE TITLE
Allow user to choose whether or not to pass file extension

### ISSUE THREAD

**Issue by jackallard17** [WhitmanCS370/alt-f4#52]
Currently, the code enforces that the user does NOT pass a file extension with the file name. This means that if a user passes `sound.wav` into the program, it will actually get interpreted as `sound.wav.wav` and cause things to blow up.

To fix this, we will need to add logic to the `validation.is_valid_path()` method to check for both cases (user is able to pass a sound file with or without its extension)

**Comment by Jacob-Burrill** [comment]
the amount of work to give the user a choice in the matter was heinous so I just made logic in validation.is_valid_path() to return a file not found error and request the user does not append .wav when accessing sounds if they decide to append .wav.
